# Generated by Django 6.0 on 2025-12-24 17:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subject_unit_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paper_content', ckeditor.fields.RichTextField(help_text='Paste the full question paper content here')),
                ('solution_content', ckeditor.fields.RichTextField(help_text='Paste the detailed solutions here')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor.fields.RichTextField()),
                ('answer_text', ckeditor.fields.RichTextField(help_text='Model Answer')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('probability', models.IntegerField(default=90, help_text='Probability percentage (e.g. 90)')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Teacher Verified')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.unit')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(help_text='Enter the full study material/summary here')),
                ('category', models.CharField(choices=[('cheat_sheet', 'Formula Cheat Sheet'), ('summary', 'One-Page Summary'), ('study_plan', '2-Hour Study Plan')], default='summary', max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.unit')),
            ],
        ),
    ]
