# Generated by Django 6.0 on 2025-12-24 18:56

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mockpaper_question_revisionmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PYQPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Summer 2023 Exam', max_length=200)),
                ('year', models.CharField(help_text='e.g. 2023', max_length=20)),
                ('paper_content', ckeditor.fields.RichTextField(help_text='Paste the question paper content here')),
                ('solution_content', ckeditor.fields.RichTextField(blank=True, help_text='Optional: Paste the solution/model answer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyq_papers', to='main.subject')),
            ],
        ),
    ]
